# Site wide configuration

title: Nemo Mobile User experience team
description: This is the team site for the Nemo Mobile user experience, including documentation to latest software and components
logo: nemo-logo.svg
teaser: nemo-logo.svg
locale:
url: https://nemomobile-ux.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /pages/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Nemo Mobile
  email:
  twitter: NemoMobile
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: https://avatars3.githubusercontent.com/u/5736443?v=3&s=200 # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
