plugins:
exclude:
    - Gemfile
    - Gemfile.lock
# Site settings
permalink: /:categories/:title/
title: NemoMobile
description: |
  'Mer-based Linux Mobile OS'
owner: NemoMobile.org # or company name
email: contact@nemomobile.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
    twitter: https://twitter.com/nemomobile
    github: https://github.com/nemomobile
